apiVersion: 1

datasources:
  - name: postgreSQL
    type: postgres
    url: 192.168.55.15:5432
    database: tank_data
    user: dashboard_user
    secureJsonData:
      password: dashboardUser
    jsonData:
      sslmode: "disable"
      postgresVersion: 14
      timescaledb: false
